// server.js এর ভেতরে শুধু এই অংশটি আপডেট করুন
exec(`yt-dlp --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" -f "best[ext=mp4]/best" -g ${source}`, (error, stdout, stderr) => {
    // বাকি কোড আগের মতোই থাকবে...
